[colors.primary]
background = "#070e15"
foreground = "#e9efeb"

[colors.cursor]
text = "#070e15"
cursor = "#e9efeb"

[colors.selection]
text = "#070e15"
background = "#e9efeb"

[colors.normal]
black = "#050b10"
red = "#857960"
green = "#82967f"
yellow = "#96937b"
blue = "#97a6bb"
magenta = "#6c7b91"
cyan = "#83a2a3"
white = "#eff3ef"

[colors.bright]
black = "#62676c"
red = "#bfae87"
green = "#a4b89b"
yellow = "#bbb999"
blue = "#bbcce7"
magenta = "#8e9fbb"
cyan = "#a5c9ca"
white = "#f3f7f3"
