# Background and foreground colors
background = #070e15
foreground = #e9efeb

# Standard colors
palette = 0=#050b10
palette = 1=#857960
palette = 2=#82967f
palette = 3=#96937b
palette = 4=#97a6bb
palette = 5=#6c7b91
palette = 6=#83a2a3
palette = 7=#eff3ef

# Bright colors
palette = 8=#62676c
palette = 9=#bfae87
palette = 10=#a4b89b
palette = 11=#bbb999
palette = 12=#bbcce7
palette = 13=#8e9fbb
palette = 14=#a5c9ca
palette = 15=#f3f7f3
