$color = rgba(7, 14, 21, 1)
$inner_color = rgba(7, 14, 21, 0.66)
$outer_color = rgba(170, 158, 124, 1)
$font_color = rgba(233, 239, 235, 1)
$placeholder_color = rgba(233, 239, 235, 0.7)
$check_color = rgba(164, 184, 155, 1)
