background            #070e15
foreground            #e9efeb

# black
color0  #050b10
color8  #62676c

# red
color1  #857960
color9  #bfae87

# green
color2  #82967f
color10 #a4b89b

# yellow
color3  #96937b
color11 #bbb999

# blue
color4  #97a6bb
color12 #bbcce7

# magenta
color5  #6c7b91
color13 #8e9fbb

#cyan
color6  #83a2a3
color14 #a5c9ca

#white
color7  #eff3ef
color15 #f3f7f3
