background            #070e15
foreground            #b1d2d2

# black
color0  #050b10
color8  #62676c

# red
color1  #857960
color9  #aa9e7c

# green
color2  #70806c
color10 #92a58b

# yellow
color3  #96937b
color11 #bbb999

# blue
color4  #97a6bb
color12 #bbcce7

# magenta
color5  #6c7b91
color13 #8e9fbb

#cyan
color6  #83a2a3
color14 #a5c9ca

#white
color7  #bdd9d9
color15 #c5dddd
