```conf
# Haven — Kitty
# Dark, muted, high-contrast, minimal.

background            #070e15
foreground            #e9efeb

# Cursor
cursor                #bfae87
cursor_text_color     #070e15

# Selection
selection_background  #20262c
selection_foreground  #f3f7f3

# URL / links
url_color             #83a2a3

# ANSI palette

# black
color0  #050b10
color8  #62676c

# red
color1  #857960
color9  #bfae87

# green
color2  #82967f
color10 #a4b89b

# yellow
color3  #96937b
color11 #bbb999

# blue
color4  #97a6bb
color12 #bbcce7

# magenta
color5  #6c7b91
color13 #8e9fbb

# cyan
color6  #83a2a3
color14 #a5c9ca

# white
color7  #e9efeb
color15 #f3f7f3

# Haven terminal appearance

background_opacity 0.92
dynamic_background_opacity yes

cursor_shape block
cursor_blink_interval 0

inactive_text_alpha 0.92

enable_audio_bell no
```
