# Background and foreground colors
background = #070e15
foreground = #b1d2d2

# Standard colors
palette = 0=#070e15
palette = 1=#857960
palette = 2=#70806c
palette = 3=#96937b
palette = 4=#97a6bb
palette = 5=#6c7b91
palette = 6=#83a2a3
palette = 7=#b1d2d2

# Bright colors
palette = 8=#62676c
palette = 9=#aa9e7c
palette = 10=#92a58b
palette = 11=#bbb999
palette = 12=#bbcce7
palette = 13=#8e9fbb
palette = 14=#a5c9ca
palette = 15=#b1d2d2
