$color = rgba(7, 14, 21, 1)
$inner_color = rgba(7, 14, 21, 0.66)
$outer_color = rgba(108, 123, 145, 1)
$font_color = rgba(177, 210, 210, 1)
$placeholder_color = rgba(177, 210, 210, 0.7)
$check_color = rgba(131, 162, 163, 1)
